spring.application.name=ProyectoSuperpet

# ⭐ API KEY DE GEMINI 
# IMPORTANTE: Esta es la API key no la suban webones xdddd
gemini.api.key=AIzaSyCscM_7WAviH4RMa2hSNFPn7x7ArRJRyp8
# MUCHAHOS LA KEY RECUERDEN XD

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/SuperPetPrueba1?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sql

# JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Seguridad
spring.security.user.name=
spring.security.user.password=

# Thymeleaf
spring.thymeleaf.cache=false




# para asegurar que las cookies no se corten(las de sesion especificamente)# Configuración de sesión
# Asegurar que las cookies persistan
server.servlet.session.cookie.max-age=1800
spring.session.store-type=none
server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m
server.servlet.session.cookie.same-site=lax


# ===============================
# CONFIGURACIÓN EMAIL (SMTP)
# ===============================
 #spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=TU_CORREO@gmail.com
#spring.mail.password=CLAVE_DE_APLICACION
#spring.mail.protocol=smtp

#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
