spring.application.name=ProyectoSuperpet

gemini.api.key=${GEMINI_API_KEY}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Seguridad
spring.security.user.name=
spring.security.user.password=

# Thymeleaf
spring.thymeleaf.cache=false




# para asegurar que las cookies no se corten(las de sesion especificamente)# Configuración de sesión
# Asegurar que las cookies persistan
server.servlet.session.cookie.max-age=1800
spring.session.store-type=none
server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m
server.servlet.session.cookie.same-site=lax

#para verlo por movil xd
server.address=0.0.0.0


